<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Deterministic>true</Deterministic>
    <NoWarn>$(NoWarn);1591;CA1001;CA1008;CA1028;CA1031;CA1054;CA1056;CA1711;CA1815;CA1819;CA5358;CA5394</NoWarn>
  </PropertyGroup>
</Project>
